language: node_js
node_js:
- 4.5.0
deploy:
  provider: heroku
  api_key:
    secure: YwqZDIamco6Mk/ws638+ScC1tCcO098O70Z9o8XZdxScvJdGWTgB3QucKRDaWnuYnw+JPAXrgWOhwDIQb+iICZMu+GTbnxJmrOeuxONNvi/447Drber+F/2uGWMnJkA7m4AJnpSfRNrRgdxWMIy0AAFz0DU8pfEL/hY0J9r1lUr+9xDcp86Me6fpQFZ6YLQ0PffWrTNtCd4puird6CEwFav3TkREYHyhTUQOHKx3bjUWtbJnXAVLTA6ND+M0QqkQTPfDhGLA2SQUKHWMKkXTVlVGwD9O6KCCeoFFzlBknVTqqlYNPYkCLZZJdNePzk8lvi/mwkU/Swxg8ztxpde3vkUUU30S0KhodBIBoTnHkLgHMfwXLvNSmbVIVKbUQd9SO91JliQkr8Oly0z6GPYL/kygilIvg5JYgBVv7WC0b1+5rK5Edm5RBZ8VmL9EnfY+N1IAqMCz+oLDP5FaE54nX1Aqq1Go9tbJgFhOahE7ErO+q+9QH4iCMqdjhFAdrSA2BDCIQxLisvWdLWThSoP1YHu5el9stG8XRm+GRf4kRUDKZ7vhDdemGDP+hOSqBgXmaS4EB/o+v16VU0OqO88f0uHjT/3MJcLiOAMUZ4sn/sXzurWRNu4gbvZSwZDGHXlhWb7MUYH+Ob41AYH/SQWtiXX0Kw02CkAgUjmXcWZl1RM=
app: obama-speeches
true:
  repo: edwinmah/obama-speeches
  branch: master
